background_color:
  type: string
  default: "rgba(var(--primary-rgb), 0.035)"
  description: "Add a background color hovering effect for topic list item on no-touch devices and tapping effect on touch devices."
tap_style:
  default: push
  type: enum
  choices:
    - background
  description: "Select the tap animation on topic list item touch devices."
